//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Criação.
        /// </summary>
        public static string AuditedEntity_CreatedDate {
            get {
                return ResourceManager.GetString("AuditedEntity_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado Por.
        /// </summary>
        public static string AuditedEntity_CreatedUser {
            get {
                return ResourceManager.GetString("AuditedEntity_CreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Actualização.
        /// </summary>
        public static string AuditedEntity_LastUpdatedDate {
            get {
                return ResourceManager.GetString("AuditedEntity_LastUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizado Por.
        /// </summary>
        public static string AuditedEntity_LastUpdatedUser {
            get {
                return ResourceManager.GetString("AuditedEntity_LastUpdatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string AuditedEntity_State {
            get {
                return ResourceManager.GetString("AuditedEntity_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idade.
        /// </summary>
        public static string Beneficiary_Age {
            get {
                return ResourceManager.GetString("Beneficiary_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiário já existe !.
        /// </summary>
        public static string Beneficiary_Beneficiary_Already_Exists {
            get {
                return ResourceManager.GetString("Beneficiary_Beneficiary_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Beneficiário.
        /// </summary>
        public static string Beneficiary_Code {
            get {
                return ResourceManager.GetString("Beneficiary_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string Beneficiary_DateOfBirth {
            get {
                return ResourceManager.GetString("Beneficiary_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento por Estimativa.
        /// </summary>
        public static string Beneficiary_DateOfBirthUnknown {
            get {
                return ResourceManager.GetString("Beneficiary_DateOfBirthUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string Beneficiary_Female {
            get {
                return ResourceManager.GetString("Beneficiary_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro Nome.
        /// </summary>
        public static string Beneficiary_FirstName {
            get {
                return ResourceManager.GetString("Beneficiary_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo.
        /// </summary>
        public static string Beneficiary_FullName {
            get {
                return ResourceManager.GetString("Beneficiary_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gênero.
        /// </summary>
        public static string Beneficiary_Gender {
            get {
                return ResourceManager.GetString("Beneficiary_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de HIV.
        /// </summary>
        public static string Beneficiary_HIVStatus {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do Estado de HIV.
        /// </summary>
        public static string Beneficiary_HIVStatus_Date {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de HIV.
        /// </summary>
        public static string Beneficiary_HIVStatus_History {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está em TARV.
        /// </summary>
        public static string Beneficiary_HIVStatus_IN_TARV {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_IN_TARV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negativo.
        /// </summary>
        public static string Beneficiary_HIVStatus_Negative {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não está em TARV.
        /// </summary>
        public static string Beneficiary_HIVStatus_NOT_IN_TARV {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_NOT_IN_TARV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Conhece.
        /// </summary>
        public static string Beneficiary_HIVStatus_NOT_KNOWN {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_NOT_KNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Recomendado.
        /// </summary>
        public static string Beneficiary_HIVStatus_NOT_RECOMMENDED {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_NOT_RECOMMENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Revelado.
        /// </summary>
        public static string Beneficiary_HIVStatus_NOT_REVEALED {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_NOT_REVEALED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positivo.
        /// </summary>
        public static string Beneficiary_HIVStatus_Positive {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminado.
        /// </summary>
        public static string Beneficiary_HIVStatus_Undetermined {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_Undetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconhecido.
        /// </summary>
        public static string Beneficiary_HIVStatus_Unknown {
            get {
                return ResourceManager.GetString("Beneficiary_HIVStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rastreio de HIV feito no Levantamento Inicial do Baneficiario.
        /// </summary>
        public static string Beneficiary_HIVTracked {
            get {
                return ResourceManager.GetString("Beneficiary_HIVTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregado.
        /// </summary>
        public static string Beneficiary_Household {
            get {
                return ResourceManager.GetString("Beneficiary_Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chefe do agregado.
        /// </summary>
        public static string Beneficiary_IsHouseHoldChef {
            get {
                return ResourceManager.GetString("Beneficiary_IsHouseHoldChef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faz parte do Grupo de Poupança.
        /// </summary>
        public static string Beneficiary_IsPartSavingGroup {
            get {
                return ResourceManager.GetString("Beneficiary_IsPartSavingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relacao c/ chefe do agregado.
        /// </summary>
        public static string Beneficiary_KinshipToFamilyHead {
            get {
                return ResourceManager.GetString("Beneficiary_KinshipToFamilyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Beneficiary_LastName {
            get {
                return ResourceManager.GetString("Beneficiary_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string Beneficiary_Male {
            get {
                return ResourceManager.GetString("Beneficiary_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outro tipo de relacao c/ chefe do Agr..
        /// </summary>
        public static string Beneficiary_OtherKinshipToFamilyHead {
            get {
                return ResourceManager.GetString("Beneficiary_OtherKinshipToFamilyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de OVC.
        /// </summary>
        public static string Beneficiary_OVCType {
            get {
                return ResourceManager.GetString("Beneficiary_OVCType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Registro do Beneficiário.
        /// </summary>
        public static string Beneficiary_RegistrationDate {
            get {
                return ResourceManager.GetString("Beneficiary_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Registo diferente de Agregado.
        /// </summary>
        public static string Beneficiary_RegistrationDateDifferentFromHouseholdDate {
            get {
                return ResourceManager.GetString("Beneficiary_RegistrationDateDifferentFromHouseholdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de escolaridade.
        /// </summary>
        public static string Beneficiary_ScholarityLevel {
            get {
                return ResourceManager.GetString("Beneficiary_ScholarityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estágio do Beneficiário.
        /// </summary>
        public static string Beneficiary_Status {
            get {
                return ResourceManager.GetString("Beneficiary_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número máximo de Adultos por Agregado é 2.
        /// </summary>
        public static string Beneficiary_Validation_MaxAdultsNumber {
            get {
                return ResourceManager.GetString("Beneficiary_Validation_MaxAdultsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do Estágio do Beneficiário.
        /// </summary>
        public static string BeneficiaryStatus_Description {
            get {
                return ResourceManager.GetString("BeneficiaryStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do Estágio do Beneficiário.
        /// </summary>
        public static string BeneficiaryStatus_RegistrationDate {
            get {
                return ResourceManager.GetString("BeneficiaryStatus_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta.
        /// </summary>
        public static string CarePlan_Answer {
            get {
                return ResourceManager.GetString("CarePlan_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação.
        /// </summary>
        public static string CarePlan_Answer_Score {
            get {
                return ResourceManager.GetString("CarePlan_Answer_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do Plano de Acção.
        /// </summary>
        public static string CarePlan_CarePlan_Date {
            get {
                return ResourceManager.GetString("CarePlan_CarePlan_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta.
        /// </summary>
        public static string CarePlan_Question {
            get {
                return ResourceManager.GetString("CarePlan_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço de Suporte.
        /// </summary>
        public static string CarePlan_SupportService {
            get {
                return ResourceManager.GetString("CarePlan_SupportService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criança já foi inserida, procure no Sistema antes de Inserir.
        /// </summary>
        public static string Child_Child_already_exist {
            get {
                return ResourceManager.GetString("Child_Child_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Matriz.
        /// </summary>
        public static string CSI_IndexDate {
            get {
                return ResourceManager.GetString("CSI_IndexDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Grelha.
        /// </summary>
        public static string CSI_ViewGrid {
            get {
                return ResourceManager.GetString("CSI_ViewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Fluxo.
        /// </summary>
        public static string CSI_ViewWorkflow {
            get {
                return ResourceManager.GetString("CSI_ViewWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benificiarios inscritos por Idade.
        /// </summary>
        public static string Dashboard_Beneficiaries_By_Age {
            get {
                return ResourceManager.GetString("Dashboard_Beneficiaries_By_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benificiarios inscritos por sexo.
        /// </summary>
        public static string Dashboard_Beneficiaries_By_Sex {
            get {
                return ResourceManager.GetString("Dashboard_Beneficiaries_By_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string Dashboard_Filters {
            get {
                return ResourceManager.GetString("Dashboard_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data deve ser inferior a data Corrente.
        /// </summary>
        public static string DateBeforeCurrentDate {
            get {
                return ResourceManager.GetString("DateBeforeCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planos de Acção.
        /// </summary>
        public static string Global_Action_Plan {
            get {
                return ResourceManager.GetString("Global_Action_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de activação.
        /// </summary>
        public static string Global_Activation_Date {
            get {
                return ResourceManager.GetString("Global_Activation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Global_Active {
            get {
                return ResourceManager.GetString("Global_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adulto.
        /// </summary>
        public static string Global_Adult {
            get {
                return ResourceManager.GetString("Global_Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adultos.
        /// </summary>
        public static string Global_Adults {
            get {
                return ResourceManager.GetString("Global_Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Global_Back {
            get {
                return ResourceManager.GetString("Global_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiários.
        /// </summary>
        public static string Global_Beneficiaries {
            get {
                return ResourceManager.GetString("Global_Beneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiario.
        /// </summary>
        public static string Global_Beneficiary {
            get {
                return ResourceManager.GetString("Global_Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico do Estado do Beneficiário.
        /// </summary>
        public static string Global_BeneficiaryStatusHistory {
            get {
                return ResourceManager.GetString("Global_BeneficiaryStatusHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de Acção.
        /// </summary>
        public static string Global_Care_Plan {
            get {
                return ResourceManager.GetString("Global_Care_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planos de Acção.
        /// </summary>
        public static string Global_Care_Plans {
            get {
                return ResourceManager.GetString("Global_Care_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criança.
        /// </summary>
        public static string Global_Child {
            get {
                return ResourceManager.GetString("Global_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crianças.
        /// </summary>
        public static string Global_Children {
            get {
                return ResourceManager.GetString("Global_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende remover ?.
        /// </summary>
        public static string Global_Confirm_Remove {
            get {
                return ResourceManager.GetString("Global_Confirm_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string Global_Create {
            get {
                return ResourceManager.GetString("Global_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matriz de Apoio à Criança.
        /// </summary>
        public static string Global_CSI {
            get {
                return ResourceManager.GetString("Global_CSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este dado encontra-se bloqueado e não pode ser alterado. Para mais detalhes, consulte o Oficial Provincial..
        /// </summary>
        public static string Global_Data_is_locked {
            get {
                return ResourceManager.GetString("Global_Data_is_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string Global_Details {
            get {
                return ResourceManager.GetString("Global_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Global_Edit {
            get {
                return ResourceManager.GetString("Global_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        public static string Global_Final_Date {
            get {
                return ResourceManager.GetString("Global_Final_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gráficos.
        /// </summary>
        public static string Global_Graphics {
            get {
                return ResourceManager.GetString("Global_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregado.
        /// </summary>
        public static string Global_Household {
            get {
                return ResourceManager.GetString("Global_Household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecho de Caso da Familia.
        /// </summary>
        public static string Global_HouseholdCaseClosure {
            get {
                return ResourceManager.GetString("Global_HouseholdCaseClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreagados.
        /// </summary>
        public static string Global_Households {
            get {
                return ResourceManager.GetString("Global_Households", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de Acompanhamento da Familia.
        /// </summary>
        public static string Global_HouseholdSupportPlan {
            get {
                return ResourceManager.GetString("Global_HouseholdSupportPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Inactivação.
        /// </summary>
        public static string Global_Inactivation_Date {
            get {
                return ResourceManager.GetString("Global_Inactivation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial.
        /// </summary>
        public static string Global_Initial_Date {
            get {
                return ResourceManager.GetString("Global_Initial_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listagem.
        /// </summary>
        public static string Global_List {
            get {
                return ResourceManager.GetString("Global_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximo.
        /// </summary>
        public static string Global_Next {
            get {
                return ResourceManager.GetString("Global_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        public static string Global_Operation_successfully_realized {
            get {
                return ResourceManager.GetString("Global_Operation_successfully_realized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activista.
        /// </summary>
        public static string Global_Partner {
            get {
                return ResourceManager.GetString("Global_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activistas.
        /// </summary>
        public static string Global_Partners {
            get {
                return ResourceManager.GetString("Global_Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activistas.
        /// </summary>
        public static string Global_Partnes {
            get {
                return ResourceManager.GetString("Global_Partnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Global_Previous {
            get {
                return ResourceManager.GetString("Global_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Província.
        /// </summary>
        public static string Global_Province {
            get {
                return ResourceManager.GetString("Global_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guia de Referência.
        /// </summary>
        public static string Global_Reference {
            get {
                return ResourceManager.GetString("Global_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Global_Remove {
            get {
                return ResourceManager.GetString("Global_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de Visita.
        /// </summary>
        public static string Global_RoutineVisit {
            get {
                return ResourceManager.GetString("Global_RoutineVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Global_Save {
            get {
                return ResourceManager.GetString("Global_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string Global_Search {
            get {
                return ResourceManager.GetString("Global_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        public static string Global_Services {
            get {
                return ResourceManager.GetString("Global_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCB.
        /// </summary>
        public static string Global_Site {
            get {
                return ResourceManager.GetString("Global_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metas.
        /// </summary>
        public static string Global_SiteGoals {
            get {
                return ResourceManager.GetString("Global_SiteGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa.
        /// </summary>
        public static string Global_Task {
            get {
                return ResourceManager.GetString("Global_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefas.
        /// </summary>
        public static string Global_Tasks {
            get {
                return ResourceManager.GetString("Global_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferir.
        /// </summary>
        public static string Global_Transfer {
            get {
                return ResourceManager.GetString("Global_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Global_User {
            get {
                return ResourceManager.GetString("Global_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários.
        /// </summary>
        public static string Global_Users {
            get {
                return ResourceManager.GetString("Global_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Inicio de TARV.
        /// </summary>
        public static string HIV_TARV_Date {
            get {
                return ResourceManager.GetString("HIV_TARV_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O primeiro estado de HIV da Criança não pode ser removido..
        /// </summary>
        public static string HIVStatus_Validation_First_HIVStatus_Cannot_Be_Removed {
            get {
                return ResourceManager.GetString("HIVStatus_Validation_First_HIVStatus_Cannot_Be_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo &apos;Em tratamento&apos;, é obrigatório quando seleccionamos a opção POSITIVO no campo &apos;Estado de HIV&apos;..
        /// </summary>
        public static string HIVStatus_Validation_HIVInTreatment_Required {
            get {
                return ResourceManager.GetString("HIVStatus_Validation_HIVInTreatment_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo &apos;Data de Estado de HIV&apos; é obrigatório..
        /// </summary>
        public static string HIVStatus_Validation_HIVStatus_Date_Required {
            get {
                return ResourceManager.GetString("HIVStatus_Validation_HIVStatus_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo &apos;Desconhecido Porque ?&apos;, é obrigatório quando seleccionamos a opção Desconhecido no campo &apos;Estado de HIV&apos;..
        /// </summary>
        public static string HIVStatus_Validation_HIVUndisclosedReason_Required {
            get {
                return ResourceManager.GetString("HIVStatus_Validation_HIVUndisclosedReason_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo &apos;Data de inicio de TARV&apos; é obrigatório, caso escolha a Opção &apos;Em TARV&apos;..
        /// </summary>
        public static string HIVStatus_Validation_INTARV_Date_Required {
            get {
                return ResourceManager.GetString("HIVStatus_Validation_INTARV_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        public static string Home_Apply {
            get {
                return ResourceManager.GetString("Home_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        public static string Home_Clear {
            get {
                return ResourceManager.GetString("Home_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregado recebe Apoio ?.
        /// </summary>
        public static string Household_Aid {
            get {
                return ResourceManager.GetString("Household_Aid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguém de cama.
        /// </summary>
        public static string Household_AnyoneBedridden {
            get {
                return ResourceManager.GetString("Household_AnyoneBedridden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarteirão.
        /// </summary>
        public static string Household_Block {
            get {
                return ResourceManager.GetString("Household_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar Conhecido Próx. de Casa.
        /// </summary>
        public static string Household_ClosePlaceToHome {
            get {
                return ResourceManager.GetString("Household_ClosePlaceToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Agregado.
        /// </summary>
        public static string Household_Code {
            get {
                return ResourceManager.GetString("Household_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distrito.
        /// </summary>
        public static string Household_District {
            get {
                return ResourceManager.GetString("Household_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável pela Familia.
        /// </summary>
        public static string Household_FamilyHead {
            get {
                return ResourceManager.GetString("Household_FamilyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem da referencia da Familia.
        /// </summary>
        public static string Household_FamilyOriginRef {
            get {
                return ResourceManager.GetString("Household_FamilyOriginRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone da Família.
        /// </summary>
        public static string Household_FamilyPhoneNumber {
            get {
                return ResourceManager.GetString("Household_FamilyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Agregado.
        /// </summary>
        public static string Household_HouseholdName {
            get {
                return ResourceManager.GetString("Household_HouseholdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero da Casa.
        /// </summary>
        public static string Household_HouseNumber {
            get {
                return ResourceManager.GetString("Household_HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string Household_NeighborhoodName {
            get {
                return ResourceManager.GetString("Household_NeighborhoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posto Administrativo.
        /// </summary>
        public static string Household_OrgUnit {
            get {
                return ResourceManager.GetString("Household_OrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activista.
        /// </summary>
        public static string Household_Partner {
            get {
                return ResourceManager.GetString("Household_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Líder Comunitário.
        /// </summary>
        public static string Household_PrincipalChiefName {
            get {
                return ResourceManager.GetString("Household_PrincipalChiefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Registo.
        /// </summary>
        public static string Household_RegistrationDate {
            get {
                return ResourceManager.GetString("Household_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregado Activo.
        /// </summary>
        public static string HouseholdStatus_Active {
            get {
                return ResourceManager.GetString("HouseholdStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado do Agregado.
        /// </summary>
        public static string HouseholdStatus_Description {
            get {
                return ResourceManager.GetString("HouseholdStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregado Inactivo.
        /// </summary>
        public static string HouseholdStatus_Inactive {
            get {
                return ResourceManager.GetString("HouseholdStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Registro do Estado do Agregado.
        /// </summary>
        public static string HouseholdStatus_RegistrationDate {
            get {
                return ResourceManager.GetString("HouseholdStatus_RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feito.
        /// </summary>
        public static string HouseholdSupportPlan_DoneStatus {
            get {
                return ResourceManager.GetString("HouseholdSupportPlan_DoneStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final do Plano Familiar.
        /// </summary>
        public static string HouseholdSupportPlan_FinalDate {
            get {
                return ResourceManager.GetString("HouseholdSupportPlan_FinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompleto.
        /// </summary>
        public static string HouseholdSupportPlan_IncompleteStatus {
            get {
                return ResourceManager.GetString("HouseholdSupportPlan_IncompleteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial do Plano Familiar.
        /// </summary>
        public static string HouseholdSupportPlan_InitialDate {
            get {
                return ResourceManager.GetString("HouseholdSupportPlan_InitialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado do Plano Familiar.
        /// </summary>
        public static string HouseholdSupportPlan_Status {
            get {
                return ResourceManager.GetString("HouseholdSupportPlan_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-MAC (Matriz de Apoio à Criança).
        /// </summary>
        public static string Layout_Footer_Application_Name {
            get {
                return ResourceManager.GetString("Layout_Footer_Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Layout_LogOff {
            get {
                return ResourceManager.GetString("Layout_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios de Dados Agregados.
        /// </summary>
        public static string Layout_Menu_Agreggated_reports {
            get {
                return ResourceManager.GetString("Layout_Menu_Agreggated_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregados familiares.
        /// </summary>
        public static string Layout_Menu_Households {
            get {
                return ResourceManager.GetString("Layout_Menu_Households", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Dados Agregados.
        /// </summary>
        public static string Layout_Menu_Manage_Agreggated_Data {
            get {
                return ResourceManager.GetString("Layout_Menu_Manage_Agreggated_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestao da alteração de dados.
        /// </summary>
        public static string Layout_Menu_Manage_Data_Lock_And_Unlock {
            get {
                return ResourceManager.GetString("Layout_Menu_Manage_Data_Lock_And_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Activistas.
        /// </summary>
        public static string Layout_Menu_Manage_Partners {
            get {
                return ResourceManager.GetString("Layout_Menu_Manage_Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de OCB&apos;s.
        /// </summary>
        public static string Layout_Menu_Manage_Sites {
            get {
                return ResourceManager.GetString("Layout_Menu_Manage_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Usuários.
        /// </summary>
        public static string Layout_Menu_Manage_Users {
            get {
                return ResourceManager.GetString("Layout_Menu_Manage_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios.
        /// </summary>
        public static string Layout_Menu_Reports {
            get {
                return ResourceManager.GetString("Layout_Menu_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visão Geral da OCB.
        /// </summary>
        public static string Layout_Menu_Site_Overview {
            get {
                return ResourceManager.GetString("Layout_Menu_Site_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relatórios da OCB.
        /// </summary>
        public static string Layout_Menu_Site_Reports {
            get {
                return ResourceManager.GetString("Layout_Menu_Site_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administração do Sistema.
        /// </summary>
        public static string Layout_Menu_System_Admin {
            get {
                return ResourceManager.GetString("Layout_Menu_System_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listas de Verificação.
        /// </summary>
        public static string Layout_Menu_Verification_Lists {
            get {
                return ResourceManager.GetString("Layout_Menu_Verification_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCB.
        /// </summary>
        public static string Layout_Site {
            get {
                return ResourceManager.GetString("Layout_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar credenciais.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticação.
        /// </summary>
        public static string Login_Screen_Title {
            get {
                return ResourceManager.GetString("Login_Screen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilize uma conta local para acessar o sistema.
        /// </summary>
        public static string Login_Use_Local_Account_to_Login {
            get {
                return ResourceManager.GetString("Login_Use_Local_Account_to_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Partner_Address {
            get {
                return ResourceManager.GetString("Partner_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Activista.
        /// </summary>
        public static string Partner_Code {
            get {
                return ResourceManager.GetString("Partner_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string Partner_Contact {
            get {
                return ResourceManager.GetString("Partner_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome à Contactar.
        /// </summary>
        public static string Partner_ContactName {
            get {
                return ResourceManager.GetString("Partner_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Partner_Fax {
            get {
                return ResourceManager.GetString("Partner_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Partner_Name {
            get {
                return ResourceManager.GetString("Partner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Partner_Role {
            get {
                return ResourceManager.GetString("Partner_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior.
        /// </summary>
        public static string Partner_Superior {
            get {
                return ResourceManager.GetString("Partner_Superior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Sanitária.
        /// </summary>
        public static string Reference_Sanitary_Unit {
            get {
                return ResourceManager.GetString("Reference_Sanitary_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acção Social.
        /// </summary>
        public static string Reference_Social_Services {
            get {
                return ResourceManager.GetString("Reference_Social_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve Selecionar alguma Referencia para o Activista.
        /// </summary>
        public static string ReferenceService_BlankActivistReferences {
            get {
                return ResourceManager.GetString("ReferenceService_BlankActivistReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Contra Referência.
        /// </summary>
        public static string ReferenceService_CounterReferenceDate {
            get {
                return ResourceManager.GetString("ReferenceService_CounterReferenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Ref. de Saúde.
        /// </summary>
        public static string ReferenceService_HealthAttendedDate {
            get {
                return ResourceManager.GetString("ReferenceService_HealthAttendedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Sanitária.
        /// </summary>
        public static string ReferenceService_HealthUnitName {
            get {
                return ResourceManager.GetString("ReferenceService_HealthUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário da Saúde.
        /// </summary>
        public static string ReferenceService_HealthWorker {
            get {
                return ResourceManager.GetString("ReferenceService_HealthWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outras Referências.
        /// </summary>
        public static string ReferenceService_Other_References {
            get {
                return ResourceManager.GetString("ReferenceService_Other_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activista.
        /// </summary>
        public static string ReferenceService_Partner {
            get {
                return ResourceManager.GetString("ReferenceService_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Ref. do Activista.
        /// </summary>
        public static string ReferenceService_ReferenceDate {
            get {
                return ResourceManager.GetString("ReferenceService_ReferenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenciado Por.
        /// </summary>
        public static string ReferenceService_ReferencedBy {
            get {
                return ResourceManager.GetString("ReferenceService_ReferencedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N# da Referência.
        /// </summary>
        public static string ReferenceService_ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceService_ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Ref. dos Serviços Sociais.
        /// </summary>
        public static string ReferenceService_SocialAttendedDate {
            get {
                return ResourceManager.GetString("ReferenceService_SocialAttendedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário dos Serviços Sociais.
        /// </summary>
        public static string ReferenceService_SocialWorker {
            get {
                return ResourceManager.GetString("ReferenceService_SocialWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do Perfil.
        /// </summary>
        public static string Role_Description {
            get {
                return ResourceManager.GetString("Role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentários.
        /// </summary>
        public static string RoutineVisit_Comments {
            get {
                return ResourceManager.GetString("RoutineVisit_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI.
        /// </summary>
        public static string RoutineVisit_DPI {
            get {
                return ResourceManager.GetString("RoutineVisit_DPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento Económico.
        /// </summary>
        public static string RoutineVisit_EconomicDevelopment {
            get {
                return ResourceManager.GetString("RoutineVisit_EconomicDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educação.
        /// </summary>
        public static string RoutineVisit_Education {
            get {
                return ResourceManager.GetString("RoutineVisit_Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebeu o Kit Familiar.
        /// </summary>
        public static string RoutineVisit_FamilyKitReceived {
            get {
                return ResourceManager.GetString("RoutineVisit_FamilyKitReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentação e Nutrição.
        /// </summary>
        public static string RoutineVisit_FoodAndNutrition {
            get {
                return ResourceManager.GetString("RoutineVisit_FoodAndNutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saúde.
        /// </summary>
        public static string RoutineVisit_Health {
            get {
                return ResourceManager.GetString("RoutineVisit_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rastreio de HIV.
        /// </summary>
        public static string RoutineVisit_HIVRisk {
            get {
                return ResourceManager.GetString("RoutineVisit_HIVRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitação.
        /// </summary>
        public static string RoutineVisit_Housing {
            get {
                return ResourceManager.GetString("RoutineVisit_Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suporte e Protecção Legal.
        /// </summary>
        public static string RoutineVisit_LegalProtectionAndSupport {
            get {
                return ResourceManager.GetString("RoutineVisit_LegalProtectionAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem beneficiários registados para crianção de uma ficha de visita..
        /// </summary>
        public static string RoutineVisit_No_Beneficiaries_Registered {
            get {
                return ResourceManager.GetString("RoutineVisit_No_Beneficiaries_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apoio Social e Psicológico.
        /// </summary>
        public static string RoutineVisit_SocialAndPsychoSupport {
            get {
                return ResourceManager.GetString("RoutineVisit_SocialAndPsychoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da visita.
        /// </summary>
        public static string RoutineVisit_VisitDate {
            get {
                return ResourceManager.GetString("RoutineVisit_VisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Visita.
        /// </summary>
        public static string RoutineVisit_VisitRecordCode {
            get {
                return ResourceManager.GetString("RoutineVisit_VisitRecordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        public static string Site_Location {
            get {
                return ResourceManager.GetString("Site_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Site_Name {
            get {
                return ResourceManager.GetString("Site_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acção.
        /// </summary>
        public static string Task_Action {
            get {
                return ResourceManager.GetString("Task_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa ?.
        /// </summary>
        public static string Task_Completed {
            get {
                return ResourceManager.GetString("Task_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Término.
        /// </summary>
        public static string Task_Finish_Date {
            get {
                return ResourceManager.GetString("Task_Finish_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro Nome.
        /// </summary>
        public static string User_FirstName {
            get {
                return ResourceManager.GetString("User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo.
        /// </summary>
        public static string User_FullName {
            get {
                return ResourceManager.GetString("User_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prazo de Inactividade.
        /// </summary>
        public static string User_InactiveDaysExceededDate {
            get {
                return ResourceManager.GetString("User_InactiveDaysExceededDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertence a OCB.
        /// </summary>
        public static string User_IsOCBUser {
            get {
                return ResourceManager.GetString("User_IsOCBUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do último Loggin.
        /// </summary>
        public static string User_LastLogin {
            get {
                return ResourceManager.GetString("User_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido.
        /// </summary>
        public static string User_LastName {
            get {
                return ResourceManager.GetString("User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário está logado.
        /// </summary>
        public static string User_LoggedOn {
            get {
                return ResourceManager.GetString("User_LoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string User_Role {
            get {
                return ResourceManager.GetString("User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCB.
        /// </summary>
        public static string User_Site {
            get {
                return ResourceManager.GetString("User_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string User_Username {
            get {
                return ResourceManager.GetString("User_Username", resourceCulture);
            }
        }
    }
}
