// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Refactor_Household_allowNullable_registrationdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refactor_Household_allowNullable_registrationdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201609261544034_Refactor_Household_allowNullable_registrationdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
