// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AlterColumn_HealthAttendedDate_for_string_in_ReferenceService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterColumn_HealthAttendedDate_for_string_in_ReferenceService));
        
        string IMigrationMetadata.Id
        {
            get { return "201710092030507_AlterColumn_HealthAttendedDate_for_string_in_ReferenceService"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
