// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Add_Columns_CreatedDate_LastUpdatedDate_CreatedUser_LastUpdatedUser_in_RoutineVisit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Columns_CreatedDate_LastUpdatedDate_CreatedUser_LastUpdatedUser_in_RoutineVisit));
        
        string IMigrationMetadata.Id
        {
            get { return "201708082126217_Add_Columns_CreatedDate_LastUpdatedDate_CreatedUser_LastUpdatedUser_in_RoutineVisit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
