// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Add_Columns_CreatedDate_LastUpdatedDate_CreatedUser_LastUpdatedUser_in_ReferenceService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Columns_CreatedDate_LastUpdatedDate_CreatedUser_LastUpdatedUser_in_ReferenceService));
        
        string IMigrationMetadata.Id
        {
            get { return "201708090613000_Add_Columns_CreatedDate_LastUpdatedDate_CreatedUser_LastUpdatedUser_in_ReferenceService"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
