namespace EFDataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class GuidTimestamp : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Adult", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.User", "User_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.User", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Partner", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Child", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Disability", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ChildStatusHistory", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ChildStatus", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CSI", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CarePlan", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CarePlanDomain", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CarePlanDomainSupportService", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Answer", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CSIDomainScore", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CSIDomain", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CSIDomainSupportService", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ServiceProvider", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ServiceProviderType", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.SupportServiceType", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Domain", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.File", "File_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.File", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Question", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.GraduationCriteria", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.GraduationCriteria", "GraduationCriteria_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.DomainCriteria", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.DomainCriteria", "DomainCriteria_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.QuestionCriteria", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.QuestionCriteria", "QuestionCriteria_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.Site", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Site", "Site_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.Location", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.SiteConfig", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Config", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ConfigType", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Service", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ServiceCategory", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ServiceTrackSection", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ServiceInstance", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ServiceTrack", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ScoreType", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Tasks", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Resources", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.HouseHold", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.OrgUnit", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.OrgUnit", "OrgUnit_Guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.OVCType", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Role", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CSIDomainSource", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.CutPoint", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.Reference", "Reference_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.Reference", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ReferenceService", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.RoutineVisitMember", "RoutineVisitMember_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.RoutineVisitMember", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.RoutineVisit", "RoutineVisit_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.RoutineVisit", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.RoutineVisitSupport", "RoutineVisitSupport_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.RoutineVisitSupport", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.ReferenceType", "ReferenceType_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.ReferenceType", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AddColumn("dbo.RoutineVisitLog", "RoutineVisitLog_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AddColumn("dbo.RoutineVisitLog", "RowVersion", c => c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"));
            AlterColumn("dbo.Adult", "AdultGuid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.ChildDisability", "childdisability_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Disability", "disability_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.ChildStatusHistory", "childstatushistory_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.ChildStatus", "childstatus_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.CSIDomainSupportService", "csidomainsupportservice_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.SupportServiceType", "supportservicetype_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Tasks", "TaskGuid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Resources", "ResourceGuid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.OVCType", "ovctype_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.CSIDomainSource", "csidomainsource_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Source", "source_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.ReferenceService", "ReferenceServiceGuid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
        }
        
        public override void Down()
        {
            AlterColumn("dbo.ReferenceService", "ReferenceServiceGuid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Source", "source_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.CSIDomainSource", "csidomainsource_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.OVCType", "ovctype_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Resources", "ResourceGuid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Tasks", "TaskGuid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.SupportServiceType", "supportservicetype_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.CSIDomainSupportService", "csidomainsupportservice_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.ChildStatus", "childstatus_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.ChildStatusHistory", "childstatushistory_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Disability", "disability_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.ChildDisability", "childdisability_guid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            AlterColumn("dbo.Adult", "AdultGuid", c => c.Guid(nullable: false, defaultValueSql: "newid()"));
            DropColumn("dbo.RoutineVisitLog", "RowVersion");
            DropColumn("dbo.RoutineVisitLog", "RoutineVisitLog_guid");
            DropColumn("dbo.ReferenceType", "RowVersion");
            DropColumn("dbo.ReferenceType", "ReferenceType_guid");
            DropColumn("dbo.RoutineVisitSupport", "RowVersion");
            DropColumn("dbo.RoutineVisitSupport", "RoutineVisitSupport_guid");
            DropColumn("dbo.RoutineVisit", "RowVersion");
            DropColumn("dbo.RoutineVisit", "RoutineVisit_guid");
            DropColumn("dbo.RoutineVisitMember", "RowVersion");
            DropColumn("dbo.RoutineVisitMember", "RoutineVisitMember_guid");
            DropColumn("dbo.ReferenceService", "RowVersion");
            DropColumn("dbo.Reference", "RowVersion");
            DropColumn("dbo.Reference", "Reference_guid");
            DropColumn("dbo.CutPoint", "RowVersion");
            DropColumn("dbo.CSIDomainSource", "RowVersion");
            DropColumn("dbo.Role", "RowVersion");
            DropColumn("dbo.OVCType", "RowVersion");
            DropColumn("dbo.OrgUnit", "OrgUnit_Guid");
            DropColumn("dbo.OrgUnit", "RowVersion");
            DropColumn("dbo.HouseHold", "RowVersion");
            DropColumn("dbo.Resources", "RowVersion");
            DropColumn("dbo.Tasks", "RowVersion");
            DropColumn("dbo.ScoreType", "RowVersion");
            DropColumn("dbo.ServiceTrack", "RowVersion");
            DropColumn("dbo.ServiceInstance", "RowVersion");
            DropColumn("dbo.ServiceTrackSection", "RowVersion");
            DropColumn("dbo.ServiceCategory", "RowVersion");
            DropColumn("dbo.Service", "RowVersion");
            DropColumn("dbo.ConfigType", "RowVersion");
            DropColumn("dbo.Config", "RowVersion");
            DropColumn("dbo.SiteConfig", "RowVersion");
            DropColumn("dbo.Location", "RowVersion");
            DropColumn("dbo.Site", "Site_guid");
            DropColumn("dbo.Site", "RowVersion");
            DropColumn("dbo.QuestionCriteria", "QuestionCriteria_guid");
            DropColumn("dbo.QuestionCriteria", "RowVersion");
            DropColumn("dbo.DomainCriteria", "DomainCriteria_guid");
            DropColumn("dbo.DomainCriteria", "RowVersion");
            DropColumn("dbo.GraduationCriteria", "GraduationCriteria_guid");
            DropColumn("dbo.GraduationCriteria", "RowVersion");
            DropColumn("dbo.Question", "RowVersion");
            DropColumn("dbo.File", "RowVersion");
            DropColumn("dbo.File", "File_guid");
            DropColumn("dbo.Domain", "RowVersion");
            DropColumn("dbo.SupportServiceType", "RowVersion");
            DropColumn("dbo.ServiceProviderType", "RowVersion");
            DropColumn("dbo.ServiceProvider", "RowVersion");
            DropColumn("dbo.CSIDomainSupportService", "RowVersion");
            DropColumn("dbo.CSIDomain", "RowVersion");
            DropColumn("dbo.CSIDomainScore", "RowVersion");
            DropColumn("dbo.Answer", "RowVersion");
            DropColumn("dbo.CarePlanDomainSupportService", "RowVersion");
            DropColumn("dbo.CarePlanDomain", "RowVersion");
            DropColumn("dbo.CarePlan", "RowVersion");
            DropColumn("dbo.CSI", "RowVersion");
            DropColumn("dbo.ChildStatus", "RowVersion");
            DropColumn("dbo.ChildStatusHistory", "RowVersion");
            DropColumn("dbo.Disability", "RowVersion");
            DropColumn("dbo.Child", "RowVersion");
            DropColumn("dbo.Partner", "RowVersion");
            DropColumn("dbo.User", "RowVersion");
            DropColumn("dbo.User", "User_guid");
            DropColumn("dbo.Adult", "RowVersion");
        }
    }
}
