// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Update_And_Order_BeneficiaryStatus_To_OriginalID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_And_Order_BeneficiaryStatus_To_OriginalID));
        
        string IMigrationMetadata.Id
        {
            get { return "201810131511518_Update_And_Order_BeneficiaryStatus_To_OriginalID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
