// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Update_degreeofkingship_Esposo_to_Code_06 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_degreeofkingship_Esposo_to_Code_06));
        
        string IMigrationMetadata.Id
        {
            get { return "201807281202023_Update_degree-of-kingship_Esposo_to_Code_06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
