// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Delete_Poverty_Proof_from_Others_in_Social_ReferenceService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Delete_Poverty_Proof_from_Others_in_Social_ReferenceService));
        
        string IMigrationMetadata.Id
        {
            get { return "201806101454182_Delete_Poverty_Proof_from_Others_in_Social_ReferenceService"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
