// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Update_Existing_Beneficiary_in_StatusHistory_without_Correct_BeneficiaryGuid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Existing_Beneficiary_in_StatusHistory_without_Correct_BeneficiaryGuid));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171015072_Update_Existing_Beneficiary_in_StatusHistory_without_Correct_BeneficiaryGuid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
