// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class CreatedUser_LastUpdatedUser_For_Entities_with_AuditedEntity_Inheritance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatedUser_LastUpdatedUser_For_Entities_with_AuditedEntity_Inheritance));
        
        string IMigrationMetadata.Id
        {
            get { return "201810251357154_CreatedUser_LastUpdatedUser_For_Entities_with_AuditedEntity_Inheritance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
