namespace EFDataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class add_Answers_for_Version2_Questions_on_Answer_Table : DbMigration
    {
        public override void Up()
        {
            Sql(@"SET IDENTITY_INSERT [File] ON");

            Sql(@"BEGIN
	                IF NOT EXISTS (SELECT * FROM [File] Where FileName = 'Yellow-Smiley2.jpg' )
	                BEGIN
		                INSERT INTO [File] (FileId, [FileName]) VALUES (153, 'Yellow-Smiley2.jpg');
		                INSERT INTO [File] (FileId, [FileName]) VALUES (154, 'Red-Smiley2.jpg');
		                INSERT INTO [File] (FileId, [FileName]) VALUES (155, 'Yellow-Smiley2.jpg');
		                INSERT INTO [File] (FileId, [FileName]) VALUES (156, 'Green-Smiley2.jpg');
	                END
                END");

            Sql(@"SET IDENTITY_INSERT [File] OFF");

            Sql(@"BEGIN
	                IF NOT EXISTS (SELECT * FROM ScoreType)
	                BEGIN
		                INSERT INTO ScoreType (Score, Rating, Color, FileID) VALUES (0, 'NA', 'Black', 153);
		                INSERT INTO ScoreType (Score, Rating, Color, FileID) VALUES (1, 'NO', 'Red', 154);
		                INSERT INTO ScoreType (Score, Rating, Color, FileID) VALUES (2, 'Sometimes', 'Yellow', 155);
		                INSERT INTO ScoreType (Score, Rating, Color, FileID) VALUES (3, 'Yes', 'Lime', 156);
	                END
                END");

            Sql(@"--N/A

                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '1 - Cumpre com o calendário de vacinação? (0-5 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '2 - Bebe água tratada?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '3 - As últimas 3 vezes que a criança sentiu-se mal, foi atendida na unidade sanitária?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '4 - A criança esteve doente nas ultimas duas semanas?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '5 - Dorme dentro de uma rede mosquiteira tratada?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '6 - Tem acesso a uma latrina limpa, ou casa de banho e acesso a água para lavar as mãos?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '7 - Teve educação acerca do HIV nos últimos 2 meses? (10 - 17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '8 - Conhece o seu estado de HIV?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '9 - A criança está em TARV (Se for HIV+)?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '10 - Teve educação ou acesso aos serviços de Saúde Sexual e Reproductiva? (10-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '11 - A criança come pelo menos duas refeições por dia?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '12 - A criança variou os alimentos nos últimos 2 dias?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '13 - A criança está inscrita no ensino pre-escolar, primário, secundário ou curso professional? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '14 - Foi à escola/escolinha todos os dias durante a semana anterior? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '15 - A criança tem uniforme escolar? (6-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '16 - A criança tem material escolar? (6-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '17 - A criança tem acompanhamento dos pais/cuidadores na vida escolar? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '18 - A criança tem um bom aproveitamento escolar? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '19 - A criança faz TPC e revisão das matérias? (6-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '20 - A criança passou de classe no ano passado? (6-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '21 - A criança é tratada de forma igual em relação as outras crianças da família?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '22 - A criança teve educação sobre direitos e deveres da criança? (3-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '23 - A criança tem registo de nascimento?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '24 - A criança foi ou é vítima de violência (psicóloga/física/sexual/negligência)?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '25 - A criança respeita aos mais velhos (não desafia nem se revolta)? (5-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '26 - A criança participa de serviços religiosos ou grupos de suporte caso deseje? (5-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '27 - Tem um bom amigo ou fala com um adulto acerca dos problemas? (5-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '28 - A criança brinca com outras crianças?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '29 - A criança está envolvida em alguma actividade onde consegue expressar a sua opinião (Família, clube escolar, CCPC, etc.)? (5-17 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '30 - O cuidador é capaz de dar exemplo de uma brincadeira que fez com a criança? (0-5 anos)' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '31 - Casa adequada, segura, seca e ventilada, com paredes e tecto fortes?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '32 - A criança beneficia das actividades de geração de renda da família (Ex: Machamba, criação de animais)?' AND QuestionVersion = 2),1,0,153)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('N/A', (SELECT QuestionID FROM  [Question] WHERE Description = '33 - O cuidador participa em algum grupo de poupança?' AND QuestionVersion = 2),1,0,153)


                --Nao
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '1 - Cumpre com o calendário de vacinação? (0-5 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '2 - Bebe água tratada?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '3 - As últimas 3 vezes que a criança sentiu-se mal, foi atendida na unidade sanitária?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '4 - A criança esteve doente nas ultimas duas semanas?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '5 - Dorme dentro de uma rede mosquiteira tratada?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '6 - Tem acesso a uma latrina limpa, ou casa de banho e acesso a água para lavar as mãos?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '7 - Teve educação acerca do HIV nos últimos 2 meses? (10 - 17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '8 - Conhece o seu estado de HIV?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '9 - A criança está em TARV (Se for HIV+)?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '10 - Teve educação ou acesso aos serviços de Saúde Sexual e Reproductiva? (10-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '11 - A criança come pelo menos duas refeições por dia?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '12 - A criança variou os alimentos nos últimos 2 dias?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '13 - A criança está inscrita no ensino pre-escolar, primário, secundário ou curso professional? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '14 - Foi à escola/escolinha todos os dias durante a semana anterior? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '15 - A criança tem uniforme escolar? (6-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '16 - A criança tem material escolar? (6-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '17 - A criança tem acompanhamento dos pais/cuidadores na vida escolar? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '18 - A criança tem um bom aproveitamento escolar? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '19 - A criança faz TPC e revisão das matérias? (6-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '20 - A criança passou de classe no ano passado? (6-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '21 - A criança é tratada de forma igual em relação as outras crianças da família?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '22 - A criança teve educação sobre direitos e deveres da criança? (3-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '23 - A criança tem registo de nascimento?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '24 - A criança foi ou é vítima de violência (psicóloga/física/sexual/negligência)?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '25 - A criança respeita aos mais velhos (não desafia nem se revolta)? (5-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '26 - A criança participa de serviços religiosos ou grupos de suporte caso deseje? (5-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '27 - Tem um bom amigo ou fala com um adulto acerca dos problemas? (5-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '28 - A criança brinca com outras crianças?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '29 - A criança está envolvida em alguma actividade onde consegue expressar a sua opinião (Família, clube escolar, CCPC, etc.)? (5-17 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '30 - O cuidador é capaz de dar exemplo de uma brincadeira que fez com a criança? (0-5 anos)' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '31 - Casa adequada, segura, seca e ventilada, com paredes e tecto fortes?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '32 - A criança beneficia das actividades de geração de renda da família (Ex: Machamba, criação de animais)?' AND QuestionVersion = 2),2,0,154)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Nao', (SELECT QuestionID FROM  [Question] WHERE Description = '33 - O cuidador participa em algum grupo de poupança?' AND QuestionVersion = 2),2,0,154)



                --Talvez
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '1 - Cumpre com o calendário de vacinação? (0-5 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '2 - Bebe água tratada?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '3 - As últimas 3 vezes que a criança sentiu-se mal, foi atendida na unidade sanitária?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '4 - A criança esteve doente nas ultimas duas semanas?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '5 - Dorme dentro de uma rede mosquiteira tratada?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '6 - Tem acesso a uma latrina limpa, ou casa de banho e acesso a água para lavar as mãos?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '7 - Teve educação acerca do HIV nos últimos 2 meses? (10 - 17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '8 - Conhece o seu estado de HIV?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '9 - A criança está em TARV (Se for HIV+)?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '10 - Teve educação ou acesso aos serviços de Saúde Sexual e Reproductiva? (10-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '11 - A criança come pelo menos duas refeições por dia?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '12 - A criança variou os alimentos nos últimos 2 dias?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '13 - A criança está inscrita no ensino pre-escolar, primário, secundário ou curso professional? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '14 - Foi à escola/escolinha todos os dias durante a semana anterior? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '15 - A criança tem uniforme escolar? (6-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '16 - A criança tem material escolar? (6-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '17 - A criança tem acompanhamento dos pais/cuidadores na vida escolar? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '18 - A criança tem um bom aproveitamento escolar? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '19 - A criança faz TPC e revisão das matérias? (6-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '20 - A criança passou de classe no ano passado? (6-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '21 - A criança é tratada de forma igual em relação as outras crianças da família?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '22 - A criança teve educação sobre direitos e deveres da criança? (3-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '23 - A criança tem registo de nascimento?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '24 - A criança foi ou é vítima de violência (psicóloga/física/sexual/negligência)?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '25 - A criança respeita aos mais velhos (não desafia nem se revolta)? (5-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '26 - A criança participa de serviços religiosos ou grupos de suporte caso deseje? (5-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '27 - Tem um bom amigo ou fala com um adulto acerca dos problemas? (5-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '28 - A criança brinca com outras crianças?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '29 - A criança está envolvida em alguma actividade onde consegue expressar a sua opinião (Família, clube escolar, CCPC, etc.)? (5-17 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '30 - O cuidador é capaz de dar exemplo de uma brincadeira que fez com a criança? (0-5 anos)' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '31 - Casa adequada, segura, seca e ventilada, com paredes e tecto fortes?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '32 - A criança beneficia das actividades de geração de renda da família (Ex: Machamba, criação de animais)?' AND QuestionVersion = 2),3,0,155)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Talvez', (SELECT QuestionID FROM  [Question] WHERE Description = '33 - O cuidador participa em algum grupo de poupança?' AND QuestionVersion = 2),3,0,155)



                --SIM
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '1 - Cumpre com o calendário de vacinação? (0-5 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '2 - Bebe água tratada?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '3 - As últimas 3 vezes que a criança sentiu-se mal, foi atendida na unidade sanitária?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '4 - A criança esteve doente nas ultimas duas semanas?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '5 - Dorme dentro de uma rede mosquiteira tratada?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '6 - Tem acesso a uma latrina limpa, ou casa de banho e acesso a água para lavar as mãos?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '7 - Teve educação acerca do HIV nos últimos 2 meses? (10 - 17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '8 - Conhece o seu estado de HIV?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '9 - A criança está em TARV (Se for HIV+)?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '10 - Teve educação ou acesso aos serviços de Saúde Sexual e Reproductiva? (10-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '11 - A criança come pelo menos duas refeições por dia?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '12 - A criança variou os alimentos nos últimos 2 dias?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '13 - A criança está inscrita no ensino pre-escolar, primário, secundário ou curso professional? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '14 - Foi à escola/escolinha todos os dias durante a semana anterior? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '15 - A criança tem uniforme escolar? (6-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '16 - A criança tem material escolar? (6-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '17 - A criança tem acompanhamento dos pais/cuidadores na vida escolar? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '18 - A criança tem um bom aproveitamento escolar? (3-5 ou 6-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '19 - A criança faz TPC e revisão das matérias? (6-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '20 - A criança passou de classe no ano passado? (6-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '21 - A criança é tratada de forma igual em relação as outras crianças da família?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '22 - A criança teve educação sobre direitos e deveres da criança? (3-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '23 - A criança tem registo de nascimento?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '24 - A criança foi ou é vítima de violência (psicóloga/física/sexual/negligência)?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '25 - A criança respeita aos mais velhos (não desafia nem se revolta)? (5-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '26 - A criança participa de serviços religiosos ou grupos de suporte caso deseje? (5-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '27 - Tem um bom amigo ou fala com um adulto acerca dos problemas? (5-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '28 - A criança brinca com outras crianças?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '29 - A criança está envolvida em alguma actividade onde consegue expressar a sua opinião (Família, clube escolar, CCPC, etc.)? (5-17 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '30 - O cuidador é capaz de dar exemplo de uma brincadeira que fez com a criança? (0-5 anos)' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '31 - Casa adequada, segura, seca e ventilada, com paredes e tecto fortes?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '32 - A criança beneficia das actividades de geração de renda da família (Ex: Machamba, criação de animais)?' AND QuestionVersion = 2),4,0,156)
                INSERT INTO  [Answer] ([Description],[QuestionID],[ScoreID],[ExcludeFromReport],[FileID]) VALUES ('Sim', (SELECT QuestionID FROM  [Question] WHERE Description = '33 - O cuidador participa em algum grupo de poupança?' AND QuestionVersion = 2),4,0,156)", false);
        }

        public override void Down()
        {
            Sql(@"DELETE answer 
                FROM  [Answer] answer 
                JOIN  [Question] question ON answer.QuestionID = question.QuestionID AND question.QuestionVersion = 2", false);

        }
    }
}
