// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class insert_value_zero_to_otherReferences_CheckBoxes_on_existing_ReferenceServices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insert_value_zero_to_otherReferences_CheckBoxes_on_existing_ReferenceServices));
        
        string IMigrationMetadata.Id
        {
            get { return "201806101353338_insert_value_zero_to_otherReferences_CheckBoxes_on_existing_ReferenceServices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
