// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_Selected_Reference_For_CheckboxList_in_Reference_Service : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Selected_Reference_For_CheckboxList_in_Reference_Service));
        
        string IMigrationMetadata.Id
        {
            get { return "201903131357486_add_Selected_Reference_For_CheckboxList_in_Reference_Service"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
