// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Setting_Order_Of_Domain_SupportService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Setting_Order_Of_Domain_SupportService));
        
        string IMigrationMetadata.Id
        {
            get { return "201903210903061_Setting_Order_Of_Domain_SupportService"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
