// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Add_New_RoutineVisit_View_and_MergedRoutineVisits_View : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_New_RoutineVisit_View_and_MergedRoutineVisits_View));
        
        string IMigrationMetadata.Id
        {
            get { return "201905240820167_Add_New_RoutineVisit_View_and_MergedRoutineVisits_View"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
