// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddHouseholdStatusAddHouseholdSupportPlanAddTARVInitialDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHouseholdStatusAddHouseholdSupportPlanAddTARVInitialDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201902211127211_AddHouseholdStatus.AddHouseholdSupportPlan.AddTARVInitialDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
