// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class UpdateSyncState_To_NeverSynced_And_LastUpdatedDate_on_HouseholdStatusHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateSyncState_To_NeverSynced_And_LastUpdatedDate_on_HouseholdStatusHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201903140708301_UpdateSyncState_To_NeverSynced_And_LastUpdatedDate_on_HouseholdStatusHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
