// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class UpdateAll_CheckBoxes_For_NewRoutineVisits_With_Todos_in_Description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateAll_CheckBoxes_For_NewRoutineVisits_With_Todos_in_Description));
        
        string IMigrationMetadata.Id
        {
            get { return "201904031857048_UpdateAll_CheckBoxes_For_NewRoutineVisits_With_Todos_in_Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
