// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class RoutineVisitDate_Missing_in_RoutineVisitMember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoutineVisitDate_Missing_in_RoutineVisitMember));
        
        string IMigrationMetadata.Id
        {
            get { return "201904180531015_RoutineVisitDate_Missing_in_RoutineVisitMember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
