// <auto-generated />
namespace EFDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddNewHouseholdStatus_And_InsertAllHouseholdsWithInitialState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNewHouseholdStatus_And_InsertAllHouseholdsWithInitialState));
        
        string IMigrationMetadata.Id
        {
            get { return "201902280518532_AddNewHouseholdStatus_And_InsertAllHouseholdsWithInitialState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
